<?php

declare(strict_types=1);

// use the autoloader generated by Composer
// It allows auto-loading of:
//   1. packages listed in require section of composer.json (i.e. dependencies)
//   2. additional classes (i.e. our app code) as specified in autoload (PSR-4) section of composer.json
// Composer autoloader (internally it always calls spl_autoload_register with prepend=true)
require __DIR__ . '/../vendor/autoload.php';

// docs:
//   https://www.php.net/autoload
//   https://www.php.net/manual/en/function.spl-autoload-register.php
//   https://getcomposer.org/doc/01-basic-usage.md
//   https://www.php-fig.org/psr/psr-4/

// spl_autoload_register(function ($class_name) {
// 	var_dump($class_name);
// 	require_once $class_name . '.php';
// });

// instead of implementing custom autoload fn
// we can make use of of the default behavior, i.e. when we pass nothing to spl_autoload_register,
// it will map classes to files this way:
//   Some\Name\Space\Class.php => some/name/space/class.php
// spl_autoload_extensions('.php');
// spl_autoload_register();

// echo "<pre>";
// var_dump(spl_autoload_functions());
// var_dump(spl_autoload_extensions());
// echo "</pre>";
